# Generated by Django 4.2.3 on 2023-08-10 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id_activo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('name_activo', models.CharField(blank=True, max_length=100)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_bank', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_bank', models.CharField(blank=True, max_length=100)),
                ('type_bank', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('postal_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_account', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('activos', models.IntegerField(default=0)),
                ('pasivos', models.IntegerField(default=0)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mov_deudor', models.BooleanField(default=False)),
                ('mov_acreedor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pasivo',
            fields=[
                ('id_pasivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('name_pasivo', models.CharField(blank=True, max_length=100)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCuentas',
            fields=[
                ('id_catalogo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('type_catalog', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patrimonio_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('saldo_intermediario', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('cliente', models.UUIDField(blank=True, default=uuid.UUID('5243c623-8f6e-4fd5-86e1-f6d4dbc1ea14'))),
                ('contador', models.UUIDField(blank=True, default=uuid.UUID('c4734c97-2eaf-4d15-8f3e-b5fa8ee5deb2'))),
                ('totalActivos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('totalPasivos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('totalAccouns', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('activos', models.ManyToManyField(blank=True, to='catalogo_cuentas.activo')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.banco')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.country')),
                ('cuentas_de_orden', models.ManyToManyField(blank=True, to='catalogo_cuentas.cuenta')),
                ('pasivos', models.ManyToManyField(blank=True, to='catalogo_cuentas.pasivo')),
            ],
        ),
    ]
