# Generated by Django 4.2.3 on 2023-08-05 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('3b7b8678-315b-4beb-a7d3-2a14aa4f8867')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('d9cd4e89-fe1f-4dc8-836b-558e675236da')),
        ),
    ]
