# Generated by Django 4.2.3 on 2023-08-05 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('ebf76ebe-de11-4091-b086-15476afa3d38')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('9ba6dfbb-9287-4156-b43d-25ee10a8d9fd')),
        ),
    ]
