# Generated by Django 4.2.3 on 2023-08-05 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0002_alter_catalogocuentas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('b7702805-c858-47f1-8094-dafef4558ae2')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('28f3f70c-9216-44b5-965f-5765ff948716')),
        ),
    ]
